default_config:

charge_advisor:
  default_authorization_status: 'Invalid'
  authorization_list:
    - id_tag: '165243'
      name: 'v0.0.1'
      authorization_status : Accepted
    - id_tag: 'v0.0.1'
      name: 'v0.0.1'
      authorization_status : Accepted    

logger:
  default: info
  logs:
    custom_components.charge_advisor: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy: